name: Build the Frontend

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Initiate GitHub Actions
      uses: actions/checkout@v2

    - name: Vercel actions for API
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.VERCEL_ARROW_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./
    
    - name: Vercel actions for frontend
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.VERCEL_ARROW_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./public