name: test
on:
   schedule:
      - cron: '0 0 * * *'

jobs:
   test_action:
      runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
           node-version: 12
      - run: echo "Hello World"
